version: "3.1"

services:

  postgres:
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: userdb
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080