version: "3.8"

services:

  React_Fe:
    image: cc/react_fe
    ports:
      - 3000:3000
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 2
        order: start-first
      rollback_config:
        parallelism: 2
        order: stop-first
    networks:
      - gateway

  HTTP_message_broker:
    image: cc/http_message_broker
    ports:
      - 5000:80
    environment:
      MOVIE_PROCESSING_ROUTE: api/movies
      USER_MANAGEMENT_PROCESSING_ROUTE: api/users
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 2
        order: start-first
      rollback_config:
        parallelism: 2
        order: stop-first
    networks:
      - gateway
      - movies
      - users

  movie_processing:
    image: cc/movies
    ports:
      - 5001:80
    environment:
      API: api_secret
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 2
        order: start-first
      rollback_config:
        parallelism: 2
        order: stop-first
    networks:
      - movies
    secrets:
      - api_secret

  user_management_processing:
    image: cc/users
    ports:
      - 5002:80
    environment:
      PGUSER_FILE: user_secret
      PGPASSWORD_FILE: pass_secret
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: userdb
      NODE_ENV: staging
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 2
      update_config:
        order: start-first
      rollback_config:
        order: stop-first
    networks:
      - users
      - db
    secrets: 
      - user_secret
      - pass_secret

  db:
    image: postgres:9.4
    ports:
      - 5432:5432
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/user_secret
      POSTGRES_DB: userdb
      POSTGRES_PASSWORD_FILE: /run/secrets/pass_secret
    networks:
      - db
      - db-adminer
    secrets: 
      - user_secret
      - pass_secret


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-adminer

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - 8081:8080
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  db-volume:
networks:
  gateway:
  movies:
  users:
  db:
  db-adminer:
secrets:
  user_secret:
    external: true
  pass_secret:
    external: true
  api_secret:
    external: true